
year <- as.numeric(params$eGRID_year) %% 1000

# Unit File -----
unt_style_map <-  c(setNames("base", glue::glue("SEQUNT{year}")) ,
                    "YEAR"     = "base",
                    "PSTATABB" = "base",
                    "PNAME"    = "base",
                    "ORISPL"   = "base",
                    "UNITID"   = "base",
                    "PRMVR"    = "base",
                    "UNTOPST"  = "base",
                    "CAPDFLAG" = "base",
                    "PRGCODE"  = "base",
                    "BOTFIRTY" = "base",
                    "NUMGEN"   = "base",
                    "FUELU1"   = "base",
                    "HRSOP"    = "base",
                    "HTIAN"    = "color2",
                    "HTIOZ"    = "color2",
                    "NOXAN"    = "color2",
                    "NOXOZ"    = "color2",
                    "SO2AN"    = "color2",
                    "CO2AN"    = "color2",
                    "HGAN"     = "color2",
                    "HTIANSRC" = "color2",
                    "HTIOZSRC" = "color2",
                    "NOXANSRC" = "color2",
                    "NOXOZSRC" = "color2",
                    "SO2SRC"   = "color2",
                    "CO2SRC"   = "color2",
                    "HGSRC"    = "color2",
                    "SO2CTLDV" = "base",
                    "NOXCTLDV" = "base",
                    "HGCTLDV"  = "base",
                    "UNTYRONL" = "base",
                    "STACKHT"  = "base")

unt_text_style_map <-  c(setNames("basic", glue::glue("SEQUNT{year}")) ,
                        "YEAR"     = "basic",
                        "PSTATABB" = "basic",
                        "PNAME"    = "basic",
                        "ORISPL"   = "basic",
                        "UNITID"   = "basic",
                        "PRMVR"    = "basic",
                        "UNTOPST"  = "basic",
                        "CAPDFLAG" = "basic",
                        "PRGCODE"  = "basic",
                        "BOTFIRTY" = "basic",
                        "NUMGEN"   = "basic",
                        "FUELU1"   = "basic",
                        "HRSOP"    = "decimal2",
                        "HTIAN"    = "integer",
                        "HTIOZ"    = "integer",
                        "NOXAN"    = "decimal2",
                        "NOXOZ"    = "decimal2",
                        "SO2AN"    = "decimal2",
                        "CO2AN"    = "decimal2",
                        "HGAN"     = "decimal2",
                        "HTIANSRC" = "basic",
                        "HTIOZSRC" = "basic",
                        "NOXANSRC" = "basic",
                        "NOXOZSRC" = "basic",
                        "SO2SRC"   = "basic",
                        "CO2SRC"   = "basic",
                        "HGSRC"    = "basic",
                        "SO2CTLDV" = "basic",
                        "NOXCTLDV" = "basic",
                        "HGCTLDV"  = "basic",
                        "UNTYRONL" = "basic",
                        "STACKHT"  = "basic")


# Gen File -----
gen_style_map <- c(setNames("base", glue::glue("SEQGEN{year}")),
                   "YEAR"      = "base",
                   "PSTATABB"  = "base", 
                   "PNAME"     = "base",
                   "ORISPL"    = "base",
                   "GENID"     = "base",
                   "NUMBLR"    = "base",
                   "GENSTAT"   = "base",
                   "PRMVR"     = "base",
                   "FUELG1"    = "base",
                   "NAMEPCAP"  = "base",
                   "CFACT"     = "base",
                   "GENNTAN"   = "color1",
                   "GENNTAN2"  = "color1", # metric
                   "GENNTOZ"   = "color1",
                   "GENNTOZ2"  = "color1", # metric
                   "GENERSRC"  = "base",
                   "GENYRONL"  = "base",
                   "GENYRRET"  = "base")

gen_text_style_map <- c(setNames("basic", glue::glue("SEQGEN{year}")),
                        "YEAR"      = "basic",
                        "PSTATABB"  = "basic", 
                        "PNAME"     = "basic",
                        "ORISPL"    = "basic",
                        "GENID"     = "basic",
                        "NUMBLR"    = "integer",
                        "GENSTAT"   = "basic",
                        "PRMVR"     = "basic",
                        "FUELG1"    = "basic",
                        "NAMEPCAP"  = "decimal2",
                        "CFACT"     = "decimal3",
                        "GENNTAN"   = "integer2",
                        "GENNTAN2"  = "integer2", # metric
                        "GENNTOZ"   = "integer2",
                        "GENNTOZ2"  = "integer2", # metric 
                        "GENERSRC"  = "basic",
                        "GENYRONL"  = "basic",
                        "GENYRRET"  = "basic")


# Plant File ----
plnt_style_map <- c(setNames("base", glue::glue("SEQPLT{year}")), 
                  "YEAR"      = "base",
                  "PSTATABB"  = "base",
                  "PNAME"     = "base",
                  "ORISPL"    = "base",
                  "OPRNAME"   = "base",
                  "OPRCODE"   = "base",
                  "UTLSRVNM"  = "base",
                  "UTLSRVID"  = "base",
                  "SECTOR"    = "base",
                  "BANAME"    = "base",
                  "BACODE"    = "base",
                  "NERC"      = "base",
                  "SUBRGN"    = "base",
                  "SRNAME"    = "base",
                  "ISORTO"    = "base",
                  "FIPSST"    = "base",
                  "FIPSCNTY"  = "base",
                  "CNTYNAME"  = "base",
                  "LAT"       = "base",
                  "LON"       = "base",
                  "CAPDFLAG"  = "base",
                  "NUMUNT"    = "base",
                  "NUMGEN"    = "base",
                  "PLPRMFL"   = "base",
                  "PLFUELCT"  = "base",
                  "COALFLAG"  = "base",
                  "CAPFAC"    = "base",
                  "NAMEPCAP"  = "base",
                  "NBFACTOR"  = "base",
                  "RMBMFLAG"  = "base",
                  "CHPFLAG"   = "base",
                  "USETHRMO"  = "base",
                  "PWRTOHT"   = "base",
                  "ELCALLOC"  = "base",
                  "PSFLAG"    = "base",
                  "PLHTIAN"   = "color1",
                  "PLHTIOZ"   = "color1",
                  "PLHTIANT"  = "color1",
                  "PLHTIOZT"  = "color1",
                  "PLNGENAN"  = "color1",
                  "PLNGENAN2"  = "color1", # metric
                  "PLNGENOZ"  = "color1",
                  "PLNGENOZ2"  = "color1", # metric
                  "PLNGENNB"  = "color1", 
                  "PLNGENNB2"  = "color1", # metric
                  "PLNOXAN"   = "color1",
                  "PLNOXOZ"   = "color1",
                  "PLSO2AN"   = "color1",
                  "PLCO2AN"   = "color1",
                  "PLCH4AN"   = "color1",
                  "PLN2OAN"   = "color1",
                  "PLCO2EQA"  = "color1",
                  "PLHGAN"    = "color1",
                  "PLNOXRTA"  = "color4",
                  "PLNOXRTA2"  = "color4", # metric
                  "PLNOXRTO"  = "color4",
                  "PLNOXRTO2"  = "color4", # metric
                  "PLSO2RTA"  = "color4",
                  "PLSO2RTA2"  = "color4", # metric
                  "PLCO2RTA"  = "color4",
                  "PLCO2RTA2"  = "color4", # metric
                  "PLCH4RTA"  = "color4",
                  "PLCH4RTA2"  = "color4", # metric
                  "PLN2ORTA"  = "color4",
                  "PLN2ORTA2"  = "color4", # metric
                  "PLC2ERTA"  = "color4",
                  "PLC2ERTA2"  = "color4", # metric
                  "PLHGRTA"   = "color4",
                  "PLHGRTA2"   = "color4", # metric
                  "PLNOXRA"   = "color5",
                  "PLNOXRO"   = "color5",
                  "PLSO2RA"   = "color5",
                  "PLCO2RA"   = "color5",
                  "PLCH4RA"   = "color5",
                  "PLN2ORA"   = "color5",
                  "PLC2ERA"   = "color5",
                  "PLHGRA"    = "color5",
                  "PLNOXCRT"  = "color6",
                  "PLNOXCRT2"  = "color6", # metric
                  "PLNOXCRO"  = "color6",
                  "PLNOXCRO2"  = "color6", # metric
                  "PLSO2CRT"  = "color6",
                  "PLSO2CRT2"  = "color6", # metric
                  "PLCO2CRT"  = "color6",
                  "PLCO2CRT2"  = "color6", # metric
                  "PLCH4CRT"  = "color6",
                  "PLCH4CRT2"  = "color6", # metric
                  "PLN2OCRT"  = "color6",
                  "PLN2OCRT2"  = "color6", # metric
                  "PLC2ECRT"  = "color6", 
                  "PLC2ECRT2"  = "color6", # metric
                  "PLHGCRT"   = "color6",
                  "PLHGCRT2"   = "color6", # metric
                  "UNNOX"     = "color2",
                  "UNNOXOZ"   = "color2",
                  "UNSO2"     = "color2", 
                  "UNCO2"     = "color2",
                  "UNCH4"     = "color2",
                  "UNN2O"     = "color2",
                  "UNCO2E"    = "color2", 
                  "UNHG"      = "color2",
                  "UNHTI"     = "color2",
                  "UNHTIOZ"   = "color2",
                  "UNHTIT"    = "color2",
                  "UNHTIOZT"  = "color2",
                  "UNNOXSRC"  = "color2",
                  "UNNOZSRC"  = "color2",
                  "UNSO2SRC"  = "color2",
                  "UNCO2SRC"  = "color2",
                  "UNCH4SRC"  = "color2",
                  "UNN2OSRC"  = "color2",
                  "UNC2ESRC"  = "color2", 
                  "UNHGSRC"   = "color2",
                  "UNHTISRC"  = "color2",
                  "UNHOZSRC"  = "color2",
                  "BIONOX"    = "color3",
                  "BIONOXOZ"  = "color3",
                  "BIOSO2"    = "color3",
                  "BIOCO2"    = "color3",
                  "BIOCH4"    = "color3",
                  "BION2O"    = "color3",
                  "BIOCO2E"   = "color3", 
                  "CHPCHTI"   = "color3",
                  "CHPCHTIOZ" = "color3",
                  "CHPNOX"    = "color3",
                  "CHPNOXOZ"  = "color3",
                  "CHPSO2"    = "color3",
                  "CHPCO2"    = "color3",
                  "CHPCH4"    = "color3", 
                  "CHPN2O"    = "color3",
                  "CHPCO2E"   = "color3", 
                  "PLHTRT"    = "base",
                  "PLGENACL"  = "color7",
                  "PLGENACL2"  = "color7", # metric
                  "PLGENAOL"  = "color7",
                  "PLGENAOL2"  = "color7", # metric
                  "PLGENAGS"  = "color7",
                  "PLGENAGS2"  = "color7", # metric
                  "PLGENANC"  = "color7",
                  "PLGENANC2"  = "color7", # metric
                  "PLGENAHY"  = "color7",
                  "PLGENAHY2"  = "color7", # metric
                  "PLGENABM"  = "color7",
                  "PLGENABM2"  = "color7", # metric
                  "PLGENAWI"  = "color7",
                  "PLGENAWI2"  = "color7", # metric
                  "PLGENASO"  = "color7",
                  "PLGENASO2"  = "color7", # metric
                  "PLGENAGT"  = "color7",
                  "PLGENAGT2"  = "color7", # metric
                  "PLGENAOF"  = "color7",
                  "PLGENAOF2"  = "color7", # metric
                  "PLGENAOP"  = "color7",
                  "PLGENAOP2"  = "color7", # metric
                  "PLGENATN"  = "color8",
                  "PLGENATN2"  = "color8", # metric
                  "PLGENATR"  = "color8",
                  "PLGENATR2"  = "color8", # metric
                  "PLGENATO"  = "color8", 
                  "PLGENATO2"  = "color8", # metric
                  "PLGENATH"  = "color9",
                  "PLGENATH2"  = "color9", # metric
                  "PLGENACY"  = "color9v2",
                  "PLGENACY2"  = "color9v2", # metric
                  "PLGENACN"  = "color9v2",
                  "PLGENACN2"  = "color9v2", # metric
                  "PLGENACO"  = "color9v2", 
                  "PLGENACO2"  = "color9v2",  # metric
                  "PLCLPR"    = "color10",
                  "PLOLPR"    = "color10",
                  "PLGSPR"    = "color10",
                  "PLNCPR"    = "color10",
                  "PLHYPR"    = "color10",
                  "PLBMPR"    = "color10",
                  "PLWIPR"    = "color10",
                  "PLSOPR"    = "color10",
                  "PLGTPR"    = "color10",
                  "PLOFPR"    = "color10",
                  "PLOPPR"    = "color10",
                  "PLTNPR"    = "color11",
                  "PLTRPR"    = "color11",
                  "PLTOPR"    = "color11", 
                  "PLTHPR"    = "color12",
                  "PLCYPR"    = "color12v2",
                  "PLCNPR"    = "color12v2", 
                  "PLCOPR"    = "color12v2")

plnt_text_style_map <- c(setNames("basic", glue::glue("SEQPLT{year}")), 
                        "YEAR"      = "basic",
                        "PSTATABB"  = "basic",
                        "PNAME"     = "basic",
                        "ORISPL"    = "basic",
                        "OPRNAME"   = "basic",
                        "OPRCODE"   = "basic",
                        "UTLSRVNM"  = "basic",
                        "UTLSRVID"  = "basic",
                        "SECTOR"    = "basic",
                        "BANAME"    = "basic",
                        "BACODE"    = "basic",
                        "NERC"      = "basic",
                        "SUBRGN"    = "basic",
                        "SRNAME"    = "basic",
                        "ISORTO"    = "basic",
                        "FIPSST"    = "basic",
                        "FIPSCNTY"  = "basic",
                        "CNTYNAME"  = "basic",
                        "LAT"       = "basic",
                        "LON"       = "basic",
                        "CAPDFLAG"  = "basic",
                        "NUMUNT"    = "integer",
                        "NUMGEN"    = "integer",
                        "PLPRMFL"   = "basic",
                        "PLFUELCT"  = "basic",
                        "COALFLAG"  = "basic",
                        "CAPFAC"    = "decimal4",
                        "NAMEPCAP"  = "decimal2",
                        "NBFACTOR"  = "decimal4",
                        "RMBMFLAG"  = "basic",
                        "CHPFLAG"   = "basic",
                        "USETHRMO"  = "integer",
                        "PWRTOHT"   = "integer",
                        "ELCALLOC"  = "decimal4",
                        "PSFLAG"    = "basic",
                        "PLHTIAN"   = "integer",
                        "PLHTIOZ"   = "integer2",
                        "PLHTIANT"  = "integer2",
                        "PLHTIOZT"  = "integer2",
                        "PLNGENAN"  = "integer2",
                        "PLNGENAN2"  = "integer2", # metric
                        "PLNGENOZ"  = "integer2",
                        "PLNGENOZ2"  = "integer2", # metric
                        "PLNGENNB"  = "integer2", 
                        "PLNGENNB2"  = "integer2", # metric
                        "PLNOXAN"   = "integer2",
                        "PLNOXOZ"   = "integer2",
                        "PLSO2AN"   = "integer2",
                        "PLCO2AN"   = "integer2",
                        "PLCH4AN"   = "integer2",
                        "PLN2OAN"   = "integer2",
                        "PLCO2EQA"  = "integer2",
                        "PLHGAN"    = "integer2",
                        "PLNOXRTA"  = "decimal4",
                        "PLNOXRTA2"  = "decimal4", # metric
                        "PLNOXRTO"  = "decimal4",
                        "PLNOXRTO2"  = "decimal4", # metric
                        "PLSO2RTA"  = "decimal4",
                        "PLSO2RTA2"  = "decimal4", # metric
                        "PLCO2RTA"  = "decimal4",
                        "PLCO2RTA2"  = "decimal4", # metric
                        "PLCH4RTA"  = "decimal4",
                        "PLCH4RTA2"  = "decimal4", # metric
                        "PLN2ORTA"  = "decimal4",
                        "PLN2ORTA2"  = "decimal4", # metric
                        "PLC2ERTA"  = "decimal4",
                        "PLC2ERTA2"  = "decimal4", # metric
                        "PLHGRTA"   = "decimal4",
                        "PLHGRTA2"   = "decimal4", # metric
                        "PLNOXRA"   = "decimal4",
                        "PLNOXRO"   = "decimal4",
                        "PLSO2RA"   = "decimal4",
                        "PLCO2RA"   = "decimal4",
                        "PLCH4RA"   = "decimal4",
                        "PLN2ORA"   = "decimal4",
                        "PLC2ERA"   = "decimal4",
                        "PLHGRA"    = "decimal4",
                        "PLNOXCRT"  = "decimal4",
                        "PLNOXCRT2"  = "decimal4", # metric
                        "PLNOXCRO"  = "decimal4",
                        "PLNOXCRO2"  = "decimal4", # metric
                        "PLSO2CRT"  = "decimal4",
                        "PLSO2CRT2"  = "decimal4", # metric
                        "PLCO2CRT"  = "decimal4",
                        "PLCO2CRT2"  = "decimal4", # metric
                        "PLCH4CRT"  = "decimal4",
                        "PLCH4CRT2"  = "decimal4", # metric
                        "PLN2OCRT"  = "decimal4",
                        "PLN2OCRT2"  = "decimal4", # metric
                        "PLC2ECRT"  = "decimal4",
                        "PLC2ECRT2"  = "decimal4", # metric
                        "PLHGCRT"   = "decimal4",
                        "PLHGCRT2"   = "decimal4", # metric
                        "UNNOX"     = "integer",
                        "UNNOXOZ"   = "integer",
                        "UNSO2"     = "integer", 
                        "UNCO2"     = "integer",
                        "UNCH4"     = "integer",
                        "UNN2O"     = "integer",
                        "UNCO2E"    = "integer", 
                        "UNHG"      = "integer",
                        "UNHTI"     = "integer",
                        "UNHTIOZ"   = "integer",
                        "UNHTIT"    = "integer", # flag
                        "UNHTIOZT"  = "integer", # flag
                        "UNNOXSRC"  = "basic",
                        "UNNOZSRC"  = "basic",
                        "UNSO2SRC"  = "basic",
                        "UNCO2SRC"  = "basic",
                        "UNCH4SRC"  = "basic",
                        "UNN2OSRC"  = "basic",
                        "UNC2ESRC"  = "basic", 
                        "UNHGSRC"   = "basic",
                        "UNHTISRC"  = "basic",
                        "UNHOZSRC"  = "basic",
                        "BIONOX"    = "integer",
                        "BIONOXOZ"  = "integer",
                        "BIOSO2"    = "integer",
                        "BIOCO2"    = "integer",
                        "BIOCH4"    = "integer",
                        "BION2O"    = "integer",
                        "BIOCO2E"   = "integer", 
                        "CHPCHTI"   = "integer",
                        "CHPCHTIOZ" = "integer",
                        "CHPNOX"    = "integer",
                        "CHPNOXOZ"  = "integer",
                        "CHPSO2"    = "decimal3", # flag
                        "CHPCO2"    = "integer2",
                        "CHPCH4"    = "integer2", 
                        "CHPN2O"    = "integer2",
                        "CHPCO2E"   = "integer2", 
                        "PLHTRT"    = "integer2",
                        "PLGENACL"  = "integer2",
                        "PLGENACL2"  = "integer2", # metric
                        "PLGENAOL"  = "integer2",
                        "PLGENAOL2"  = "integer2", # metric
                        "PLGENAGS"  = "integer2",
                        "PLGENAGS2"  = "integer2", # metric
                        "PLGENANC"  = "integer2",
                        "PLGENANC2"  = "integer2", # metric
                        "PLGENAHY"  = "integer2",
                        "PLGENAHY2"  = "integer2", # metric
                        "PLGENABM"  = "integer2",
                        "PLGENABM2"  = "integer2", # metric
                        "PLGENAWI"  = "integer2",
                        "PLGENAWI2"  = "integer2", # metric
                        "PLGENASO"  = "integer2",
                        "PLGENASO2"  = "integer2", # metric
                        "PLGENAGT"  = "integer2",
                        "PLGENAGT2"  = "integer2", # metric
                        "PLGENAOF"  = "integer2",
                        "PLGENAOF2"  = "integer2", # metric
                        "PLGENAOP"  = "integer2",
                        "PLGENAOP2"  = "integer2", # metric
                        "PLGENATN"  = "integer2",
                        "PLGENATN2"  = "integer2", # metric
                        "PLGENATR"  = "integer2",
                        "PLGENATR2"  = "integer2", # metric
                        "PLGENATO"  = "integer2", 
                        "PLGENATO2"  = "integer2",  # metric
                        "PLGENATH"  = "integer2",
                        "PLGENATH2"  = "integer2", # metric
                        "PLGENACY"  = "integer2",
                        "PLGENACY2"  = "integer2", # metric
                        "PLGENACN"  = "integer2",
                        "PLGENACN2"  = "integer2", # metric
                        "PLGENACO"  = "integer2", 
                        "PLGENACO2"  = "integer2",  # metric
                        "PLCLPR"    = "percent",
                        "PLOLPR"    = "percent",
                        "PLGSPR"    = "percent",
                        "PLNCPR"    = "percent",
                        "PLHYPR"    = "percent",
                        "PLBMPR"    = "percent",
                        "PLWIPR"    = "percent",
                        "PLSOPR"    = "percent",
                        "PLGTPR"    = "percent",
                        "PLOFPR"    = "percent",
                        "PLOPPR"    = "percent",
                        "PLTNPR"    = "percent",
                        "PLTRPR"    = "percent",
                        "PLTOPR"    = "percent", 
                        "PLTHPR"    = "percent",
                        "PLCYPR"    = "percent",
                        "PLCNPR"    = "percent", 
                        "PLCOPR"    = "percent")

# Region Aggregations ----
region_style_map <- c("NAMEPCAP" = "base",
                      "HTIAN"    = "color1",	
                      "HTIOZ"    = "color1",	
                      "HTIANT"   = "color1",
                      "HTIOZT"   = "color1",	
                      "NGENAN"   = "color1",	
                      "NGENAN2"   = "color1", # metric
                      "NGENOZ"   = "color1",
                      "NGENOZ2"   = "color1", # metric
                      "NGENNB"   = "color1",
                      "NGENNB2"   = "color1", # metric
                      "NOXAN"    = "color1",	
                      "NOXOZ"    = "color1",	
                      "SO2AN"    = "color1",	
                      "CO2AN"    = "color1",
                      "CH4AN"    = "color1",	
                      "N2OAN"    = "color1",	
                      "CO2EQA"   = "color1",	
                      "HGAN"     = "color1",
                      "NOXRTA"   = "color4",
                      "NOXRTA2"   = "color4", # metric
                      "NOXRTO"   = "color4",	
                      "NOXRTO2"   = "color4",	# metric
                      "SO2RTA"   = "color4",	
                      "SO2RTA2"   = "color4",	# metric
                      "CO2RTA"   = "color4",	
                      "CO2RTA2"   = "color4",	# metric
                      "CH4RTA"   = "color4",
                      "CH4RTA2"   = "color4", # metric
                      "N2ORTA"   = "color4",
                      "N2ORTA2"   = "color4", # metric
                      "C2ERTA"   = "color4",
                      "C2ERTA2"   = "color4", # metric
                      "HGRTA"    = "color4",
                      "HGRTA2"    = "color4", # metric
                      "NOXRA"    = "color5",
                      "NOXRO"    = "color5",
                      "SO2RA"    = "color5",	
                      "CO2RA"    = "color5",
                      "CH4RA"    = "color5",	
                      "N2ORA"    = "color5",	
                      "C2ERA"    = "color5",	
                      "HGRA"     = "color5",	
                      "NOXCRT"   = "color6",
                      "NOXCRT2"   = "color6", # metric
                      "NOXCRO"   = "color6",	
                      "NOXCRO2"   = "color6",	# metric
                      "SO2CRT"   = "color6",
                      "SO2CRT2"   = "color6", # metric
                      "CO2CRT"   = "color6",	
                      "CO2CRT2"   = "color6",	# metric
                      "CH4CRT"   = "color6",	
                      "CH4CRT2"   = "color6",	# metric
                      "N2OCRT"   = "color6",	
                      "N2OCRT2"   = "color6",	# metric
                      "C2ECRT"   = "color6",
                      "C2ECRT2"   = "color6", # metric
                      "HGCRT"    = "color6",	
                      "HGCRT2"    = "color6",	# metric
                      "CNOXRT"   = "color13",	
                      "CNOXRT2"   = "color13", # metric
                      "ONOXRT"   = "color13",	
                      "ONOXRT2"   = "color13",	# metric
                      "GNOXRT"   = "color13",	
                      "GNOXRT2"   = "color13", # metric
                      "FSNXRT"   = "color13",	
                      "FSNXRT2"   = "color13",	# metric
                      "CNXORT"   = "color13",
                      "CNXORT2"   = "color13", # metric
                      "ONXORT"   = "color13",	
                      "ONXORT2"   = "color13",	# metric
                      "GNXORT"   = "color13",	
                      "GNXORT2"   = "color13",	# metric
                      "FSNORT"   = "color13",
                      "FSNORT2"   = "color13", # metric
                      "CSO2RT"   = "color13",	
                      "CSO2RT2"   = "color13",	# metric
                      "OSO2RT"   = "color13",	
                      "OSO2RT2"   = "color13",	# metric
                      "GSO2RT"   = "color13",	
                      "GSO2RT2"   = "color13",	# metric
                      "FSS2RT"   = "color13",
                      "FSS2RT2"   = "color13", # metric
                      "CCO2RT"   = "color13",	
                      "CCO2RT2"   = "color13",	# metric
                      "OCO2RT"   = "color13",	
                      "OCO2RT2"   = "color13",	# metric
                      "GCO2RT"   = "color13",	
                      "GCO2RT2"   = "color13",	# metric
                      "FSC2RT"   = "color13",	
                      "FSC2RT2"   = "color13",	# metric
                      "CCH4RT"   = "color13",
                      "CCH4RT2"   = "color13", # metric
                      "OCH4RT"   = "color13",	
                      "OCH4RT2"   = "color13",	# metric
                      "GCH4RT"   = "color13",	
                      "GCH4RT2"   = "color13",	# metric
                      "FCH4RT"   = "color13",	
                      "FCH4RT2"   = "color13",	# metric
                      "CN2ORT"   = "color13",
                      "CN2ORT2"   = "color13", # metric
                      "ON2ORT"   = "color13",	
                      "ON2ORT2"   = "color13",	# metric
                      "GN2ORT"   = "color13",
                      "GN2ORT2"   = "color13", # metric
                      "FN2ORT"   = "color13",	
                      "FN2ORT2"   = "color13",	# metric
                      "CC2ERT"   = "color13",	
                      "CC2ERT2"   = "color13",	# metric
                      "OC2ERT"   = "color13",
                      "OC2ERT2"   = "color13", # metric
                      "GC2ERT"   = "color13",	
                      "GC2ERT2"   = "color13",	# metric
                      "FSC2ERT"  = "color13",	
                      "FSC2ERT2"  = "color13",	# metric
                      "CHGRT"    = "color13",	
                      "CHGRT2"    = "color13",	# metric
                      "FSHGRT"   = "color13",
                      "FSHGRT2"   = "color13", # metric
                      "CNOXR"    = "color14",
                      "ONOXR"    = "color14",	
                      "GNOXR"    = "color14",	
                      "FSNXR"    = "color14",	
                      "CNXOR"    = "color14",	
                      "ONXOR"    = "color14",	
                      "GNXOR"    = "color14",	
                      "FSNOR"    = "color14",
                      "CSO2R"    = "color14",	
                      "OSO2R"    = "color14",	
                      "GSO2R"    = "color14",	
                      "FSS2R"    = "color14",	
                      "CCO2R"    = "color14",	
                      "OCO2R"    = "color14",	
                      "GCO2R"    = "color14",	
                      "FSC2R"    = "color14",	
                      "CCH4R"    = "color14",	
                      "OCH4R"    = "color14",	
                      "GCH4R"    = "color14",
                      "FCH4R"    = "color14",	
                      "CN2OR"    = "color14",
                      "ON2OR"    = "color14",	
                      "GN2OR"    = "color14",	
                      "FN2OR"    = "color14",	
                      "CC2ER"    = "color14",	
                      "OC2ER"    = "color14",	
                      "GC2ER"    = "color14",	
                      "FSC2ER"   = "color14",	
                      "CHGR"     = "color14",	
                      "FSHGR"    = "color14",	
                      "NBNOX"    = "color15",	
                      "NBNOX2"    = "color15",	# metric
                      "NBNXO"    = "color15",	
                      "NBNXO2"    = "color15",	# metric
                      "NBSO2"    = "color15",	
                      "NBSO22"    = "color15",	# metric
                      "NBCO2"    = "color15",
                      "NBCO22"    = "color15", # metric
                      "NBCH4"    = "color15",	
                      "NBCH42"    = "color15",	# metric
                      "NBN2O"    = "color15",	
                      "NBN2O2"    = "color15",	# metric
                      "NBC2E"    = "color15",	
                      "NBC2E2"    = "color15",	# metric
                      "NBHG"     = "color15",	
                      "NBHG2"     = "color15",	# metric
                      "GENACL"   = "color7",	
                      "GENACL2"   = "color7",	# metric
                      "GENAOL"   = "color7",	
                      "GENAOL2"   = "color7", # metric
                      "GENAGS"   = "color7",	
                      "GENAGS2"   = "color7",	# metric
                      "GENANC"   = "color7",	
                      "GENANC2"   = "color7",	# metric
                      "GENAHY"   = "color7",	
                      "GENAHY2"   = "color7",	# metric
                      "GENABM"   = "color7",	
                      "GENABM2"   = "color7",	# metric
                      "GENAWI"   = "color7",	
                      "GENAWI2"   = "color7",	# metric
                      "GENASO"   = "color7",	
                      "GENASO2"   = "color7", # metric
                      "GENAGT"   = "color7",	
                      "GENAGT2"   = "color7",	# metric
                      "GENAOF"   = "color7",	
                      "GENAOF2"   = "color7",	# metric
                      "GENAOP"   = "color7",	
                      "GENAOP2"   = "color7",	# metric
                      "GENATN"   = "color8",	
                      "GENATN2"   = "color8",	# metric
                      "GENATR"   = "color8",	
                      "GENATR2"   = "color8", # metric
                      "GENATO"   = "color8", 
                      "GENATO2"   = "color8", # metric
                      "GENATH"   = "color9",	
                      "GENATH2"   = "color9",	# metric
                      "GENACY"   = "color9v2",
                      "GENACY2"   = "color9v2", # metric
                      "GENACN"   = "color9v2",
                      "GENACN2"   = "color9v2", # metric
                      "GENACO"   = "color9v2", 
                      "GENACO2"   = "color9v2", # metric
                      "CLPR"     = "color10",
                      "OLPR"     = "color10",	
                      "GSPR"     = "color10",	
                      "NCPR"     = "color10",	
                      "HYPR"     = "color10",	
                      "BMPR"     = "color10",
                      "WIPR"     = "color10",	
                      "SOPR"     = "color10",
                      "GTPR"     = "color10",	
                      "OFPR"     = "color10",
                      "OPPR"     = "color10",
                      "TNPR"     = "color11",	
                      "TRPR"     = "color11",	
                      "TOPR"     = "color11", 
                      "THPR"     = "color12",	
                      "CYPR"     = "color12v2",	
                      "CNPR"     = "color12v2",
                      "COPR"     = "color12v2", 
                      "NBGNCL"   = "color16",	
                      "NBGNCL2"   = "color16",	# metric
                      "NBGNOL"   = "color16",	
                      "NBGNOL2"   = "color16",	# metric
                      "NBGNGS"   = "color16",	
                      "NBGNGS2"   = "color16",	# metric
                      "NBGNNC"   = "color16",	
                      "NBGNNC2"   = "color16",	# metric
                      "NBGNHY"   = "color16",	
                      "NBGNHY2"   = "color16",	# metric
                      "NBGNBM"   = "color16",	
                      "NBGNBM2"   = "color16", # metric
                      "NBGNWI"   = "color16",	
                      "NBGNWI2"   = "color16",	# metric
                      "NBGNSO"   = "color16",
                      "NBGNSO2"   = "color16", # metric
                      "NBGNGT"   = "color16",	
                      "NBGNGT2"   = "color16",	# metric
                      "NBGNOF"   = "color16",
                      "NBGNOF2"   = "color16", # metric
                      "NBGNOP"   = "color16",	
                      "NBGNOP2"   = "color16",	# metric
                      "NBCLPR"   = "color17",	
                      "NBOLPR"   = "color17",	
                      "NBGSPR"   = "color17",	
                      "NBNCPR"   = "color17",	
                      "NBHYPR"   = "color17",	
                      "NBBMPR"   = "color17",	
                      "NBWIPR"   = "color17",	
                      "NBSOPR"   = "color17",	
                      "NBGTPR"   = "color17",	
                      "NBOFPR"   = "color17",	
                      "NBOPPR"   = "color17")

region_text_style_map <- c("NAMEPCAP" = "integer2",
                           "HTIAN"    = "integer2",	
                           "HTIOZ"    = "integer2",	
                           "HTIANT"   = "integer2",
                           "HTIOZT"   = "integer2",	
                           "NGENAN"   = "integer2",	
                           "NGENAN2"   = "integer2",	# metric
                           "NGENOZ"   = "integer2",
                           "NGENOZ2"   = "integer2", # metric
                           "NGENNB"   = "integer2",
                           "NGENNB2"   = "integer2", # metric
                           "NOXAN"    = "integer2",	
                           "NOXOZ"    = "integer2",	
                           "SO2AN"    = "integer2",	
                           "CO2AN"    = "integer2",
                           "CH4AN"    = "integer2",	
                           "N2OAN"    = "integer2",	
                           "CO2EQA"   = "integer2",	
                           "HGAN"     = "integer2",
                           "NOXRTA"   = "decimal1",
                           "NOXRTA2"   = "decimal1", # metric
                           "NOXRTO"   = "decimal1",	
                           "NOXRTO2"   = "decimal1",	# metric
                           "SO2RTA"   = "decimal1",	
                           "SO2RTA2"   = "decimal1",	# metric
                           "CO2RTA"   = "decimal1",	
                           "CO2RTA2"   = "decimal1",	# metric
                           "CH4RTA"   = "decimal1",
                           "CH4RTA2"   = "decimal1", # metric
                           "N2ORTA"   = "decimal1",
                           "N2ORTA2"   = "decimal1", # metric
                           "C2ERTA"   = "decimal1",
                           "C2ERTA2"   = "decimal1", # metric
                           "HGRTA"    = "decimal1",
                           "HGRTA2"    = "decimal1", # metric
                           "NOXRA"    = "decimal1",
                           "NOXRO"    = "decimal1",
                           "SO2RA"    = "decimal1",	
                           "CO2RA"    = "decimal1",
                           "CH4RA"    = "decimal1",	
                           "N2ORA"    = "decimal1",	
                           "C2ERA"    = "decimal1",	
                           "HGRA"     = "decimal1",	
                           "NOXCRT"   = "decimal1",
                           "NOXCRT2"   = "decimal1", # metric
                           "NOXCRO"   = "decimal1",	
                           "NOXCRO2"   = "decimal1",	# metric
                           "SO2CRT"   = "decimal1",
                           "SO2CRT2"   = "decimal1", # metric
                           "CO2CRT"   = "decimal1",	
                           "CO2CRT2"   = "decimal1",	# metric
                           "CH4CRT"   = "decimal1",	
                           "CH4CRT2"   = "decimal1",	# metric
                           "N2OCRT"   = "decimal1",	
                           "N2OCRT2"   = "decimal1",	# metric
                           "C2ECRT"   = "decimal1",
                           "C2ECRT2"   = "decimal1", # metric
                           "HGCRT"    = "decimal1",	
                           "HGCRT2"    = "decimal1",	# metric
                           "CNOXRT"   = "decimal1",	
                           "CNOXRT2"   = "decimal1",	# metric
                           "ONOXRT"   = "decimal1",	
                           "ONOXRT2"   = "decimal1",	# metric
                           "GNOXRT"   = "decimal1",	
                           "GNOXRT2"   = "decimal1",	# metric
                           "FSNXRT"   = "decimal1",	
                           "FSNXRT2"   = "decimal1",	# metric
                           "CNXORT"   = "decimal1",
                           "CNXORT2"   = "decimal1", # metric
                           "ONXORT"   = "decimal1",	
                           "ONXORT2"   = "decimal1",	# metric
                           "GNXORT"   = "decimal1",	
                           "GNXORT2"   = "decimal1",	# metric
                           "FSNORT"   = "decimal1",
                           "FSNORT2"   = "decimal1", # metric
                           "CSO2RT"   = "decimal1",	
                           "CSO2RT2"   = "decimal1",	# metric
                           "OSO2RT"   = "decimal1",	
                           "OSO2RT2"   = "decimal1",	# metric
                           "GSO2RT"   = "decimal1",	
                           "GSO2RT2"   = "decimal1",	# metric
                           "FSS2RT"   = "decimal1",
                           "FSS2RT2"   = "decimal1", # metric
                           "CCO2RT"   = "decimal1",	
                           "CCO2RT2"   = "decimal1",	# metric
                           "OCO2RT"   = "decimal1",	
                           "OCO2RT2"   = "decimal1",	# metric
                           "GCO2RT"   = "decimal1",	
                           "GCO2RT2"   = "decimal1",	# metric
                           "FSC2RT"   = "decimal1",	
                           "FSC2RT2"   = "decimal1",	# metric
                           "CCH4RT"   = "decimal4",
                           "CCH4RT2"   = "decimal4", # metric
                           "OCH4RT"   = "decimal4",	
                           "OCH4RT2"   = "decimal4",	# metric
                           "GCH4RT"   = "decimal4",	
                           "GCH4RT2"   = "decimal4",	# metric
                           "FCH4RT"   = "decimal4",	
                           "FCH4RT2"   = "decimal4",	 # metric
                           "CN2ORT"   = "decimal4",
                           "CN2ORT2"   = "decimal4", # metric
                           "ON2ORT"   = "decimal4",	
                           "ON2ORT2"   = "decimal4", # metric
                           "GN2ORT"   = "decimal4",
                           "GN2ORT2"   = "decimal4", # metric
                           "FN2ORT"   = "decimal4",	
                           "FN2ORT2"   = "decimal4",	# metric
                           "CC2ERT"   = "decimal1",	
                           "CC2ERT2"   = "decimal1",	# metric
                           "OC2ERT"   = "decimal1",
                           "OC2ERT2"   = "decimal1", # metric
                           "GC2ERT"   = "decimal1",	
                           "GC2ERT2"   = "decimal1",	# metric
                           "FSC2ERT"  = "decimal1",	
                           "FSC2ERT2"  = "decimal1",	# metric
                           "CHGRT"    = "decimal1",	
                           "CHGRT2"    = "decimal1",	# metric
                           "FSHGRT"   = "decimal1", 
                           "FSHGRT2"   = "decimal1", # metric
                           "CNOXR"    = "decimal1",
                           "ONOXR"    = "decimal1",	
                           "GNOXR"    = "decimal1",	
                           "FSNXR"    = "decimal1",	
                           "CNXOR"    = "decimal1",	
                           "ONXOR"    = "decimal1",	
                           "GNXOR"    = "decimal1",	
                           "FSNOR"    = "decimal1",
                           "CSO2R"    = "decimal1",	
                           "OSO2R"    = "decimal1",	
                           "GSO2R"    = "decimal1",	
                           "FSS2R"    = "decimal1",	
                           "CCO2R"    = "decimal1",	
                           "OCO2R"    = "decimal1",	
                           "GCO2R"    = "decimal1",	
                           "FSC2R"    = "decimal1",	
                           "CCH4R"    = "decimal4",	
                           "OCH4R"    = "decimal4",	
                           "GCH4R"    = "decimal4",
                           "FCH4R"    = "decimal4",	
                           "CN2OR"    = "decimal4",
                           "ON2OR"    = "decimal4",	
                           "GN2OR"    = "decimal4",	
                           "FN2OR"    = "decimal4",	
                           "CC2ER"    = "decimal1",	
                           "OC2ER"    = "decimal1",	
                           "GC2ER"    = "decimal1",	
                           "FSC2ER"   = "decimal1",	
                           "CHGR"     = "decimal1",	
                           "FSHGR"    = "decimal1",	
                           "NBNOX"    = "decimal1",	
                           "NBNOX2"    = "decimal1",	# metric
                           "NBNXO"    = "decimal1",	
                           "NBNXO2"    = "decimal1", # metric
                           "NBSO2"    = "decimal1",	
                           "NBSO22"    = "decimal1",	# metric
                           "NBCO2"    = "decimal1",
                           "NBCO22"    = "decimal1", # metric
                           "NBCH4"    = "decimal1",	
                           "NBCH42"    = "decimal1",	# metric
                           "NBN2O"    = "decimal1",	
                           "NBN2O2"    = "decimal1",	 # metric
                           "NBC2E"    = "decimal1",	
                           "NBC2E2"    = "decimal1",	# metric
                           "NBHG"     = "decimal1",	
                           "NBHG2"     = "decimal1",	# metric
                           "GENACL"   = "integer2",	
                           "GENACL2"   = "integer2",	# metric
                           "GENAOL"   = "integer2",	
                           "GENAOL2"   = "integer2",	# metric
                           "GENAGS"   = "integer2",	
                           "GENAGS2"   = "integer2",	# metric
                           "GENANC"   = "integer2",	
                           "GENANC2"   = "integer2",	# metric
                           "GENAHY"   = "integer2",	
                           "GENAHY2"   = "integer2",	# metric
                           "GENABM"   = "integer2",	
                           "GENABM2"   = "integer2",	# metric
                           "GENAWI"   = "integer2",	
                           "GENAWI2"   = "integer2",	# metric
                           "GENASO"   = "integer2",	
                           "GENASO2"   = "integer2",	# metric
                           "GENAGT"   = "integer2",	
                           "GENAGT2"   = "integer2",	# metric
                           "GENAOF"   = "integer2",	
                           "GENAOF2"   = "integer2",	# metric
                           "GENAOP"   = "integer2",	
                           "GENAOP2"   = "integer2",	# metric
                           "GENATN"   = "integer2",	
                           "GENATN2"   = "integer2",	# metric
                           "GENATR"   = "integer2",	
                           "GENATR2"   = "integer2",	# metric
                           "GENATO"   = "integer2", 
                           "GENATO2"   = "integer2", # metric
                           "GENATH"   = "integer2",	
                           "GENATH2"   = "integer2",	# metric
                           "GENACY"   = "integer2",
                           "GENACY2"   = "integer2", # metric
                           "GENACN"   = "integer2",
                           "GENACN2"   = "integer2", # metric
                           "GENACO"   = "integer2", 
                           "GENACO2"   = "integer2", # metric
                           "CLPR"     = "percent", # percent
                           "OLPR"     = "percent",	
                           "GSPR"     = "percent",	
                           "NCPR"     = "percent",	
                           "HYPR"     = "percent",	
                           "BMPR"     = "percent",
                           "WIPR"     = "percent",	
                           "SOPR"     = "percent",
                           "GTPR"     = "percent",	
                           "OFPR"     = "percent",
                           "OPPR"     = "percent",
                           "TNPR"     = "percent",	
                           "TRPR"     = "percent",	
                           "TOPR"     = "percent", 
                           "THPR"     = "percent",	
                           "CYPR"     = "percent",	
                           "CNPR"     = "percent",
                           "COPR"     = "percent", 
                           "NBGNCL"   = "integer2",	
                           "NBGNCL2"   = "integer2",	# metric
                           "NBGNOL"   = "integer2",	
                           "NBGNOL2"   = "integer2",	# metric
                           "NBGNGS"   = "integer2",	
                           "NBGNGS2"   = "integer2",	# metric
                           "NBGNNC"   = "integer2",	
                           "NBGNNC2"   = "integer2",	# metric
                           "NBGNHY"   = "integer2",	
                           "NBGNHY2"   = "integer2",	# metric
                           "NBGNBM"   = "integer2",	
                           "NBGNBM2"   = "integer2", # metric
                           "NBGNWI"   = "integer2",	
                           "NBGNWI2"   = "integer2",	# metric
                           "NBGNSO"   = "integer2",
                           "NBGNSO2"   = "integer2", # metric
                           "NBGNGT"   = "integer2",	
                           "NBGNGT2"   = "integer2",	# metric
                           "NBGNOF"   = "integer2",
                           "NBGNOF2"   = "integer2", # metric
                           "NBGNOP"   = "integer2",	
                           "NBGNOP2"   = "integer2",	# metric
                           "NBCLPR"   = "percent",	
                           "NBOLPR"   = "percent",	
                           "NBGSPR"   = "percent",	
                           "NBNCPR"   = "percent",	
                           "NBHYPR"   = "percent",	
                           "NBBMPR"   = "percent",	
                           "NBWIPR"   = "percent",	
                           "NBSOPR"   = "percent",	
                           "NBGTPR"   = "percent",	
                           "NBOFPR"   = "percent",	
                           "NBOPPR"   = "percent")
# GGL File ----

ggl_style_map <- c("YEAR"  = "base",
                   "REGION" = "base",
                   "ESTLOSS" = "base",
                   "ESTLOSS2" = "base", # metric
                   "TOTDISP" = "base", 
                   "TOTDISP2" = "base", # metric
                   "DIRCTUSE" = "base",
                   "DIRCTUSE2" = "base", # metric
                   "GGRSLOSS" = "base")

ggl_text_style_map <- c("YEAR" = "basic",
                        "REGION" = "basic",
                        "ESTLOSS" = "integer",
                        "ESTLOSS2" = "integer", # metric
                        "TOTDISP" = "integer", 
                        "TOTDISP2" = "integer", # metric
                        "DIRCTUSE" = "integer",
                        "DIRCTUSE2" = "integer", # metric
                        "GGRSLOSS" = "percent")