## -------------------------------
##
## Function region formatting
## 
## Purpose: 
## 
## This file formats all of the outputs created for eGRID 
## This includes all operating units for the specified eGRID data year
##
## For data or manual changes that need to be checked every year, they are denoted with this note:
## ### Note: check for updates or changes each data year ###
##
## Authors:  
##      Madeline Zhang, Abt Global
##
## -------------------------------

create_region_formatting <- function(region){
  standard_header <- c("NAMEPCAP",	
                       "HTIAN",	
                       "HTIOZ",	
                       "HTIANT",
                       "HTIOZT",	
                       "NGENAN",	
                       "NGENOZ",
                       "NOXAN",	
                       "NOXOZ",	
                       "SO2AN",	
                       "CO2AN",
                       "CH4AN",	
                       "N2OAN",	
                       "CO2EQA",	
                       "HGAN",
                       "NOXRTA",
                       "NOXRTO",	
                       "SO2RTA",	
                       "CO2RTA",	
                       "CH4RTA",
                       "N2ORTA",
                       "C2ERTA",
                       "HGRTA",
                       "NOXRA",
                       "NOXRO",
                       "SO2RA",	
                       "CO2RA",
                       "CH4RA",	
                       "N2ORA",	
                       "C2ERA",	
                       "HGRA",	
                       "NOXCRT",
                       "NOXCRO",	
                       "SO2CRT",
                       "CO2CRT",	
                       "CH4CRT",	
                       "N2OCRT",	
                       "C2ECRT",
                       "HGCRT",	
                       "CNOXRT",	
                       "ONOXRT",	
                       "GNOXRT",	
                       "FSNXRT",	
                       "CNXORT",
                       "ONXORT",	
                       "GNXORT",	
                       "FSNORT",
                       "CSO2RT",	
                       "OSO2RT",	
                       "GSO2RT",	
                       "FSS2RT",
                       "CCO2RT",	
                       "OCO2RT",	
                       "GCO2RT",	
                       "FSC2RT",	
                       "CCH4RT",
                       "OCH4RT",	
                       "GCH4RT",	
                       "FCH4RT",	
                       "CN2ORT",
                       "ON2ORT",	
                       "GN2ORT",
                       "FN2ORT",	
                       "CC2ERT",	
                       "OC2ERT",
                       "GC2ERT",	
                       "FSC2ERT",	
                       "CHGRT",	
                       "FSHGRT",
                       "CNOXR",
                       "ONOXR",	
                       "GNOXR",	
                       "FSNXR",	
                       "CNXOR",	
                       "ONXOR",	
                       "GNXOR",	
                       "FSNOR",
                       "CSO2R",	
                       "OSO2R",	
                       "GSO2R",	
                       "FSS2R",	
                       "CCO2R",	
                       "OCO2R",	
                       "GCO2R",	
                       "FSC2R",	
                       "CCH4R",	
                       "OCH4R",	
                       "GCH4R",
                       "FCH4R",	
                       "CN2OR",
                       "ON2OR",	
                       "GN2OR",	
                       "FN2OR",	
                       "CC2ER",	
                       "OC2ER",	
                       "GC2ER",	
                       "FSC2ER",	
                       "CHGR",	
                       "FSHGR",	
                       "NBNOX",	
                       "NBNXO",	
                       "NBSO2",	
                       "NBCO2",
                       "NBCH4",	
                       "NBN2O",	
                       "NBC2E",	
                       "NBHG",	
                       "GENACL",	
                       "GENAOL",	
                       "GENAGS",	
                       "GENANC",	
                       "GENAHY",	
                       "GENABM",	
                       "GENAWI",	
                       "GENASO",	
                       "GENAGT",	
                       "GENAOF",	
                       "GENAOP",	
                       "GENATN",	
                       "GENATR",	
                       "GENATH",	
                       "GENACY",
                       "GENACN",	
                       "CLPR",
                       "OLPR",	
                       "GSPR",	
                       "NCPR",	
                       "HYPR",	
                       "BMPR",
                       "WIPR",	
                       "SOPR",
                       "GTPR",	
                       "OFPR",
                       "OPPR",
                       "TNPR",	
                       "TRPR",	
                       "THPR",	
                       "CYPR",	
                       "CNPR",	
                       "NBGNCL",	
                       "NBGNOL",	
                       "NBGNGS",	
                       "NBGNNC",	
                       "NBGNHY",	
                       "NBGNBM",	
                       "NBGNWI",	
                       "NBGNSO",
                       "NBGNGT",	
                       "NBGNOF",
                       "NBGNOP",	
                       "NBCLPR",	
                       "NBOLPR",	
                       "NBGSPR",	
                       "NBNCPR",	
                       "NBHYPR",	
                       "NBBMPR",	
                       "NBWIPR",	
                       "NBSOPR",	
                       "NBGTPR",	
                       "NBOFPR",	
                       "NBOPPR")
  
  standard_desc <- c("nameplate capacity (MW)",
                     "annual heat input from combustion (MMBtu)",
                     "ozone season heat input from combustion (MMBtu)", 
                     "total annual heat input (MMBtu)",
                     "total ozone season heat input (MMBtu)",
                     "annual net generation (MWh)",
                     "ozone season net generation (MWh)",
                     "annual NOx emissions (tons)",
                     "ozone season NOx emissions (tons)",
                     "annual SO2 emissions (tons)",
                     "annual CO2 emissions (tons)",
                     "annual CH4 emissions (lbs)",
                     "annual N2O emissions (lbs)",
                     "annual CO2 equivalent emissions (tons)",
                     "annual Hg emissions (lbs)",
                     "annual NOx total output emission rate (lb/MWh)",
                     "ozone season NOx total output emission rate (lb/MWh)",
                     "annual SO2 total output emission rate (lb/MWh)",
                     "annual CO2 total output emission rate (lb/MWh)",
                     "annual CH4 total output emission rate (lb/MWh)",
                     "annual N2O total output emission rate (lb/MWh)",
                     "annual CO2 equivalent total output emission rate (lb/MWh)",
                     "annual Hg total output emission rate (lb/MWh)",
                     "annual NOx input emission rate (lb/MMBtu)",
                     "ozone season NOx input emission rate (lb/MMBtu)",
                     "annual SO2 input emission rate (lb/MMBtu)",
                     "annual CO2 input emission rate (lb/MMBtu)",
                     "annual CH4 input emission rate (lb/MMBtu)",
                     "annual N2O input emission rate (lb/MMBtu)", 
                     "annual CO2 equivalent input emission rate (lb/MMBtu)",
                     "annual Hg input emission rate (lb/MMBtu)",
                     "annual NOx combustion output emission rate (lb/MWh)",
                     "ozone season NOx combustion output emission rate (lb/MWh)",
                     "annual SO2 combustion output emission rate (lb/MWh)",
                     "annual CO2 combustion output emission rate (lb/MWh)",
                     "annual CH4 combustion output emission rate (lb/MWh)",
                     "annual N2O combustion output emission rate (lb/MWh)",
                     "annual CO2 equivalent combustion output emission rate (lb/MWh)",
                     "Hg combustion output emission rate (lb/MWh)",
                     "annual NOx coal output emission rate (lb/MWh)",
                     "annual NOx oil output emission rate (lb/MWh)", 
                     "annual NOx gas output emission rate (lb/MWh)",
                     "annual NOx fossil fuel output emission rate (lb/MWh)",
                     "ozone season NOx coal output emission rate (lb/MWh)",
                     "ozone season NOx oil output emission rate (lb/MWh)",
                     "ozone season NOx gas output emission rate (lb/MWh)",
                     "ozone season NOx fossil fuel output emission rate (lb/MWh)",
                     "annual SO2 coal output emission rate (lb/MWh)",
                     "annual SO2 oil output emission rate (lb/MWh)",
                     "annual SO2 gas output emission rate (lb/MWh)",
                     "annual SO2 fossil fuel output emission rate (lb/MWh)",
                     "annual CO2 coal output emission rate (lb/MWh)",
                     "annual CO2 oil output emission rate (lb/MWh)",
                     "annual CO2 gas output emission rate (lb/MWh)",
                     "annual CO2 fossil fuel output emission rate (lb/MWh)",
                     "annual CH4 coal output emission rate (lb/MWh)",
                     "annual CH4 oil output emission rate (lb/MWh)",
                     "annual CH4 gas output emission rate (lb/MWh)",
                     "annual CH4 fossil fuel output emission rate (lb/MWh)",
                     "annual N2O coal output emission rate (lb/MWh)",
                     "annual N2O oil output emission rate (lb/MWh)",
                     "annual N2O gas output emission rate (lb/MWh)",
                     "annual N2O fossil fuel output emission rate (lb/MWh)",
                     "annual CO2 equivalent coal output emission rate (lb/MWh)",
                     "annual CO2 equivalent oil output emission rate (lb/MWh)",
                     "annual CO2 equivalent gas output emission rate (lb/MWh)",
                     "annual CO2 equivalent fossil fuel output emission rate (lb/MWh)",
                     "annual Hg coal output emission rate (lb/MWh)",
                     "annual Hg fossil fuel output emission rate (lb/MWh)",
                     "annual NOx coal input emission rate (lb/MMBtu)",
                     "annual NOx oil input emission rate (lb/MMBtu)",
                     "annual NOx gas input emission rate (lb/MMBtu)",
                     "annual NOx fossil fuel input emission rate (lb/MMBtu)",
                     "ozone season NOx coal input emission rate (lb/MMBtu)",
                     "ozone season NOx oil input emission rate (lb/MMBtu)",
                     "ozone season NOx gas input emission rate (lb/MMBtu)",
                     "ozone season NOx fossil fuel input emission rate (lb/MMBtu)",
                     "annual SO2 coal input emission rate (lb/MMBtu)",
                     "annual SO2 oil input emission rate (lb/MMBtu)",
                     "annual SO2 gas input emission rate (lb/MMBtu)",
                     "annual SO2 fossil fuel input emission rate (lb/MMBtu)",
                     "annual CO2 coal input emission rate (lb/MMBtu)",
                     "annual CO2 oil input emission rate (lb/MMBtu)",
                     "annual CO2 gas input emission rate (lb/MMBtu)",
                     "annual CO2 fossil fuel input emission rate (lb/MMBtu)",
                     "annual CH4 coal input emission rate (lb/MMBtu)",
                     "annual CH4 oil input emission rate (lb/MMBtu)",
                     "annual CH4 gas input emission rate (lb/MMBtu)", 
                     "annual CH4 fossil fuel input emission rate (lb/MMBtu)",
                     "State annual N2O coal input emission rate (lb/MMBtu)",
                     "annual N2O oil input emission rate (lb/MMBtu)",
                     "annual N2O gas input emission rate (lb/MMBtu)",
                     "annual N2O fossil fuel input emission rate (lb/MMBtu)",
                     "annual CO2 equivalent coal input emission rate (lb/MMBtu)",
                     "annual CO2 equivalent oil input emission rate (lb/MMBtu)", 
                     "annual CO2 equivalent gas input emission rate (lb/MMBtu)",
                     "annual CO2 equivalent fossil fuel input emission rate (lb/MMBtu)",
                     "annual Hg coal input emission rate (lb/MMBtu)",
                     "annual Hg fossil fuel input emission rate (lb/MMBtu)",
                     "annual NOx non-baseload output emission rate (lb/MWh)",
                     "ozone season NOx non-baseload output emission rate (lb/MWh)",
                     "annual SO2 non-baseload output emission rate (lb/MWh)",
                     "annual CO2 non-baseload output emission rate (lb/MWh)",
                     "annual CH4 non-baseload output emission rate (lb/MWh)",
                     "annual N2O non-baseload output emission rate (lb/MWh)",
                     "annual CO2 equivalent non-baseload output emission rate (lb/MWh)",
                     "annual Hg non-baseload output emission rate (lb/MWh)",
                     "annual coal net generation (MWh)",
                     "annual oil net generation (MWh)",
                     "annual gas net generation (MWh)",
                     "annual nuclear net generation (MWh)",
                     "annual hydro net generation (MWh)",
                     "annual biomass net generation (MWh)",
                     "annual wind net generation (MWh)",
                     "annual solar net generation (MWh)",
                     "annual geothermal net generation (MWh)",
                     "annual other fossil net generation (MWh)",
                     "annual other unknown/ purchased fuel net generation (MWh)",
                     "annual total nonrenewables net generation (MWh)",
                     "annual total renewables net generation (MWh)",
                     "annual total nonhydro renewables net generation (MWh)",
                     "annual total combustion net generation (MWh)",
                     "annual total noncombustion net generation (MWh)",
                     "coal generation percent (resource mix)",
                     "oil generation percent (resource mix)",
                     "gas generation percent (resource mix)",
                     "nuclear generation percent (resource mix)",
                     "hydro generation percent (resource mix)",
                     "biomass generation percent (resource mix)",
                     "wind generation percent (resource mix)",
                     "solar generation percent (resource mix)",
                     "geothermal generation percent (resource mix)",
                     "other fossil generation percent (resource mix)",
                     "other unknown/ purchased fuel generation percent (resource mix)",
                     "total nonrenewables generation percent (resource mix)",
                     "total renewables generation percent (resource mix)",
                     "total nonhydro renewables generation percent (resource mix)",
                     "total combustion generation percent (resource mix)",
                     "total noncombustion generation percent (resource mix)",
                     "annual nonbaseload coal net generation (MWh)",
                     "annual nonbaseload oil net generation (MWh)",
                     "annual nonbaseload gas net generation (MWh)",
                     "annual nonbaseload nuclear net generation (MWh)",
                     "annual nonbaseload hydro net generation (MWh)",
                     "annual nonbaseload biomass net generation (MWh)",
                     "annual nonbaseload wind net generation (MWh)",
                     "annual nonbaseload solar net generation (MWh)",
                     "annual nonbaseload geothermal net generation (MWh)",
                     "annual nonbaseload other fossil net generation (MWh)",
                     "annual nonbaseload other unknown/ purchased fuel net generation (MWh)",
                     "nonbaseload coal generation percent (resource mix)",
                     "nonbaseload oil generation percent (resource mix)",
                     "nonbaseload gas generation percent (resource mix)",
                     "nonbaseload nuclear generation percent (resource mix)",
                     "nonbaseload hydro generation percent (resource mix)",
                     "nonbaseload biomass generation percent (resource mix)",
                     "nonbaseload wind generation percent (resource mix)",
                     "nonbaseload solar generation percent (resource mix)",
                     "nonbaseload geothermal generation percent (resource mix)",
                     "nonbaseload other fossil generation percent (resource mix)",
                     "nonbaseload other unknown/ purchased fuel generation percent (resource mix)")
}